version: '3.8'

services:
  app:
    build: .  # Utilise le Dockerfile dans le même répertoire
    container_name: symfony_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: symfony_web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:latest
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root      # Définition du mot de passe pour l'utilisateur root
      MYSQL_DATABASE: adopte_dev     # Nom de la base de données par défaut
      MYSQL_USER: root               # Utilisateur principal (root ici)
      MYSQL_PASSWORD: root           # Mot de passe de l'utilisateur root
    volumes:
      - db_data:/var/lib/mysql       # Volume pour stocker les données MySQL
    ports:
      - "3306:3306"                  # Expose MySQL pour un accès externe si nécessaire

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"                    # Accès à phpMyAdmin via http://localhost:8081
    environment:
      PMA_HOST: db                   # Nom du service MySQL (doit correspondre à 'db')
      PMA_USER: root                 # Utilisateur MySQL
      PMA_PASSWORD: root             # Mot de passe MySQL (doit correspondre à MYSQL_PASSWORD)
    depends_on:
      - db

volumes:
  db_data:
